### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by ywarnier** [ONLYOFFICE/onlyoffice-chamilo#20]
In version 1.2.0 (in comparison with version 1.0), a series of code syntax checks that exist in Chamilo 1.11.x since years ago are now flashing because somehow you seem to have gone in reverse in comparison to previous versions of the plugin.

For example:
- We require PHPDoc comment lines to end with a dot and version 1.2.0 specifically removes many of them.
- Control structures like if, while, foreach, etc require a space before the opening parenthesis, but it has been removed.
- We use no space around dots in concatenations, but some were added back.
- We use no space before the opening parenthesis for functions, but some were added.

We generally use PSR-2 with a few specifics (see https://github.com/chamilo/chamilo-lms/wiki/Coding-conventions). Is there a way we could ensure, if we send you a PR with those syntax issues fixed, that future changes would not bring those back?

Let me be clear: these do *not* affect code behaviour, so they do not introduce consistency issues in the software, but they do light up a series of warnings in automated code quality tests.

**Comment by alexanderonlyoffice** [comment]
@ywarnier,  we will try to bring the code in accordance with PSR-2 within the next connector app release. You are welcome to submit a PR, we will check it for sure. You can also suggest changes to action https://github.com/ONLYOFFICE/onlyoffice-chamilo/blob/master/.github/workflows/lint.yml.

**Comment by LinneyS** [comment]
https://github.com/ONLYOFFICE/onlyoffice-chamilo/commit/2b84f7a2732a6b8e9fd3b2429c54673c6fb7cdee
