### ISSUE TITLE
Chamilo 1.11.28 releasing soon

### ISSUE THREAD

**Issue by ywarnier** [ONLYOFFICE/onlyoffice-chamilo#37]
Hey people,

We are expecting to release Chamilo 1.11.28 on the 15th or 16th of October (next week). I see you sent a large number of changes to the `develop` branch since version 1.3. Do you expect to want to finalize this in a version 1.4 soon ? I'm asking to see if we can include this in release 1.11.28 (as you know, we prefer to have all plugins *included* in our releases).

**Comment by ywarnier** [comment]
@LinneyS ping

**Comment by SergeyKorneyev** [comment]
Hello,
We just released version 1.4 of the plugin that you can use in the release: https://github.com/ONLYOFFICE/onlyoffice-chamilo/releases/tag/v1.4.0

**Comment by ywarnier** [comment]
Thanks
