### ISSUE TITLE
View documents in learning paths

### ISSUE THREAD

**Issue by ywarnier** [ONLYOFFICE/onlyoffice-chamilo#41]
Add the possibility to see office documents through the ONLYOFFICE viewer from inside the learning paths of Chamilo.

**Comment by SergeyKorneyev** [comment]
Should we hurry add this to the integration now or can it wait until the next connector version? Please also specify when you're planning to release the next version of Chamilo and whether or not you would be willing to wait for us to create the feature before you release it.

**Comment by ywarnier** [comment]
I think it would be better for you to go ahead and release a 1.5 package with the corrections already made. I can't finish this straight away but I will add this to our release and then we can upstream this here later. Normally, we should be releasing 1.11.28 tomorrow, so a 1.5 package would be great.

**Comment by LinneyS** [comment]
https://github.com/chamilo/chamilo-lms/issues/5395
